language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:tmsz-kapela/valgrind-pmem
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev valgrind
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
script: make cstyle && make -j2 && make -j2 test && make check
env:
  - EXTRA_CFLAGS=-DUSE_VALGRIND
  - EXTRA_CFLAGS=
